version: "3.8"
services:
    telegraf:
        image: telegraf
        ports:
            - 8125:8125/udp
        volumes:
            - ./telegraf/conf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
        links:
            - influxdb
    influxdb:
        image: influxdb:alpine
        hostname: influx-grafana
        expose:
            - 8086
        environment:
            - INFLUXDB_REPORTING_DISABLED=true
            - INFLUXDB_DB=tickdemo
            - INFLUXDB_ADMIN_USER=admin
            - INFLUXDB_ADMIN_PASSWORD=admin
        volumes:
            - ./influxdb/data:/var/lib/influxdb
            - ./influxdb/config/influxdb.conf:/etc/influxdb/influxdb.conf:ro
    grafana:
        image: grafana/grafana:8.1.3
        ports:
            - "3000:3000"
        volumes:
            - "./grafana/data:/var/lib/grafana"
